# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Call for Papers
    url: /#workshop-description
    weight: 20
  - name: Schedule
    url: /#schedule
    weight: 30
  - name: Organizer Committee
    url: /#organizers
    weight: 40
  - name: Advisory Board
    url: /#advisors
    weight: 50
  - name: Contact
    url: /#contact
    weight: 60
